# Generated by Django 5.0.2 on 2025-08-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_student_assessment_status_student_placement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='placement_status',
            field=models.CharField(choices=[('Not Placed', 'Not Placed'), ('Placed', 'Placed')], default='Not Placed', max_length=20),
        ),
    ]
