# Generated by Django 5.0.2 on 2025-08-22 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_webcamconfiguration_attendance_camera_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_faces_detected', models.IntegerField(default=0)),
                ('total_faces_recognized', models.IntegerField(default=0)),
                ('total_unrecognized_faces', models.IntegerField(default=0)),
                ('total_recognized_not_assessed', models.IntegerField(default=0)),
                ('active_cameras', models.IntegerField(default=0)),
                ('active_sessions', models.IntegerField(default=0)),
                ('average_processing_time', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='detection_frame',
            field=models.TextField(blank=True, help_text='Base64 encoded detection frame', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='face_bbox',
            field=models.TextField(blank=True, help_text='JSON encoded face bounding box', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='processing_time',
            field=models.FloatField(default=0.0, help_text='Time taken for face detection and recognition'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='camerastream',
            name='attendance_auto_mark',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='camerastream',
            name='auto_start',
            field=models.BooleanField(default=False, help_text='Automatically start detection on this camera'),
        ),
        migrations.AddField(
            model_name='camerastream',
            name='confidence_threshold',
            field=models.FloatField(default=0.8, help_text='Minimum confidence for face recognition'),
        ),
        migrations.AddField(
            model_name='camerastream',
            name='connection_status',
            field=models.CharField(default='Unknown', help_text='Last known connection status', max_length=20),
        ),
        migrations.AddField(
            model_name='camerastream',
            name='face_detection_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='camerastream',
            name='is_persistent',
            field=models.BooleanField(default=True, help_text='Whether to auto-load this camera on startup'),
        ),
        migrations.AddField(
            model_name='camerastream',
            name='last_connection_test',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camerastream',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='detectionlog',
            name='detection_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional detection metadata'),
        ),
        migrations.AddField(
            model_name='detectionlog',
            name='frame_data',
            field=models.TextField(blank=True, help_text='Base64 encoded frame data', null=True),
        ),
        migrations.AddField(
            model_name='detectionlog',
            name='recognition_accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='detectionlog',
            name='unrecognized_faces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='face_embedding',
            field=models.TextField(blank=True, help_text='Stored face embedding for recognition', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='face_embedding_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='recognition_confidence',
            field=models.FloatField(default=0.0, help_text='Average recognition confidence'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='camera_type',
            field=models.CharField(choices=[('CCTV', 'CCTV Camera'), ('WEBCAM', 'Laptop Webcam')], default='CCTV', max_length=10),
        ),
        migrations.CreateModel(
            name='RecognitionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_frames_processed', models.IntegerField(default=0)),
                ('total_faces_detected', models.IntegerField(default=0)),
                ('total_faces_recognized', models.IntegerField(default=0)),
                ('average_processing_time', models.FloatField(default=0.0)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.camerastream')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UnrecognizedFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_embedding', models.TextField(help_text='Face embedding data')),
                ('face_image', models.TextField(help_text='Base64 encoded face image')),
                ('detection_time', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved for Student Creation'), ('IGNORED', 'Ignored'), ('PROCESSED', 'Processed')], default='PENDING', max_length=20)),
                ('suggested_name', models.CharField(blank=True, max_length=100, null=True)),
                ('suggested_roll_number', models.CharField(blank=True, max_length=20, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('camera_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.camerastream')),
            ],
            options={
                'ordering': ['-detection_time'],
            },
        ),
    ]
