# Generated by Django 5.0.2 on 2025-08-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_student_branch_student_phone_number_student_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assessment_status',
            field=models.CharField(choices=[('Not Assessed', 'Not Assessed'), ('Assessed', 'Assessed'), ('Under Review', 'Under Review'), ('Completed', 'Completed')], default='Not Assessed', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='placement_status',
            field=models.CharField(choices=[('Not Placed', 'Not Placed'), ('Placed', 'Placed'), ('Internship', 'Internship'), ('Higher Studies', 'Higher Studies')], default='Not Placed', max_length=20),
        ),
    ]
