# Generated by Django 5.0.2 on 2025-08-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_student_placement_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebcamConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Webcam', max_length=100)),
                ('device_id', models.IntegerField(default=0, help_text='Webcam device ID (0 for built-in camera)')),
                ('is_enabled', models.BooleanField(default=True)),
                ('auto_start', models.BooleanField(default=False, help_text='Automatically start webcam on system startup')),
                ('resolution_width', models.IntegerField(default=1280)),
                ('resolution_height', models.IntegerField(default=720)),
                ('fps', models.IntegerField(default=30)),
                ('face_detection_enabled', models.BooleanField(default=True)),
                ('attendance_auto_mark', models.BooleanField(default=True, help_text='Automatically mark attendance when face is recognized')),
                ('confidence_threshold', models.FloatField(default=0.8, help_text='Minimum confidence score for face recognition')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webcam Configuration',
                'verbose_name_plural': 'Webcam Configurations',
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='camera_type',
            field=models.CharField(choices=[('CCTV', 'CCTV Camera'), ('WEBCAM', 'Laptop Webcam')], default='CCTV', max_length=20),
        ),
        migrations.AddField(
            model_name='camerastream',
            name='camera_type',
            field=models.CharField(choices=[('CCTV', 'CCTV/IP Camera'), ('WEBCAM', 'Laptop Webcam')], default='CCTV', max_length=10),
        ),
        migrations.AddField(
            model_name='camerastream',
            name='fps',
            field=models.IntegerField(default=30, help_text='Frames per second'),
        ),
        migrations.AddField(
            model_name='camerastream',
            name='resolution_height',
            field=models.IntegerField(default=720, help_text='Camera resolution height'),
        ),
        migrations.AddField(
            model_name='camerastream',
            name='resolution_width',
            field=models.IntegerField(default=1280, help_text='Camera resolution width'),
        ),
        migrations.AddField(
            model_name='camerastream',
            name='webcam_device_id',
            field=models.IntegerField(default=0, help_text='Device ID for webcam (usually 0 for built-in camera)'),
        ),
        migrations.AddField(
            model_name='detectionlog',
            name='camera_type',
            field=models.CharField(choices=[('CCTV', 'CCTV Camera'), ('WEBCAM', 'Laptop Webcam')], default='CCTV', max_length=20),
        ),
        migrations.AddField(
            model_name='detectionlog',
            name='confidence_scores',
            field=models.JSONField(blank=True, default=list, help_text='List of confidence scores for detected faces'),
        ),
    ]
