# Generated by Django 5.0.2 on 2025-08-23 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_realtimestats_attendance_detection_frame_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='reference_image',
        ),
        migrations.AddField(
            model_name='student',
            name='liveness_confidence_score',
            field=models.FloatField(default=0.0, help_text='Liveness detection confidence score'),
        ),
        migrations.AddField(
            model_name='student',
            name='liveness_verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='liveness_verified',
            field=models.BooleanField(default=False, help_text='Whether liveness detection was completed'),
        ),
        migrations.CreateModel(
            name='LivenessDetectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('center_frame_data', models.TextField(blank=True, help_text='Base64 encoded center frame', null=True)),
                ('left_frame_data', models.TextField(blank=True, help_text='Base64 encoded left frame', null=True)),
                ('right_frame_data', models.TextField(blank=True, help_text='Base64 encoded right frame', null=True)),
                ('center_embedding', models.TextField(blank=True, help_text='Face embedding from center position', null=True)),
                ('left_embedding', models.TextField(blank=True, help_text='Face embedding from left position', null=True)),
                ('right_embedding', models.TextField(blank=True, help_text='Face embedding from right position', null=True)),
                ('center_verified', models.BooleanField(default=False)),
                ('left_verified', models.BooleanField(default=False)),
                ('right_verified', models.BooleanField(default=False)),
                ('liveness_score', models.FloatField(default=0.0, help_text='Overall liveness detection score')),
                ('movement_verified', models.BooleanField(default=False, help_text='Whether movement was detected and verified')),
                ('final_embedding', models.TextField(blank=True, help_text='Final face embedding for registration', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('attempts_count', models.IntegerField(default=0, help_text='Number of liveness detection attempts')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
